#!/bin/bash
{
cykl=$1
cas=$2
hdn=${cas%%[^0-9]*}
cs=${cas##*[0-9]}
for (( c=1; c<$cykl; c++ ))
do  for (( b=1; b<=$hdn; b++ ))
		do echo $b"/"$cas"  "$c"/"$cykl > ~/alarmtmp
			sleep 1$cs
		done
	dn=
    madplay -Q -a-20 -r$c ~/bin/pin.mp3
done
for (( b=1; b<=$hdn; b++ ))
	do echo $b"/"$cas"  "$c"/"$cykl > ~/alarmtmp
		sleep 1$cs
	done
madplay -Q -a-20 -r$c ~/bin/pin.mp3
echo "  " > ~/alarmtmp

} &
