#!/bin/bash
{
cykl=$1
cas=$2
for (( c=1; c<=$cykl; c++ ))
do  echo "a "$cas" ("$c"/"$cykl")" > ~/alarmtmp
    sleep $cas
    madplay -Q -a-20 -r$c C:/PRG/xdwl/pin.mp3
done
echo "a     " > ~/alarmtmp

} &